### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [deadtrickster/ssl_verify_fun.erl#21]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by deadtrickster** [comment]
Hi, what is up with Travis? I  can of course create the file, .github/workflows/tests.yml is ok?

**Comment by paulo-ferraz-oliveira** [comment]
Whatever name you prefer is fine. I can work with `tests.yml`, sure.

---

I don't know all the details of what's up with Travis CI, but I know a while back they opened .com, started limiting access to .org, have caused some confusion with free tiers, etc. and are now ultimately putting travis-ci.org into maintenance, come Dec 31 2020. GitHub Actions is a viable alternative, it seems. I will keep `.travis.yml` but it'll eventually stop working, I imagine.
